server:
  port: 8888

logging:
  level:
    org:
      springframework: INFO
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///D:/FunCode/app-service/config-server/src/main/local-config-server

        #default-label: master
  application:
    name: ConfgiServer